export const SET_REGIONS = 'SET_REGIONS'
export const HTTP_LOADING = 'HTTP_LOADING'
export const HTTP_LOADED = 'HTTP_LOADED'
export const HTTP_ERROR = 'HTTP_ERROR'
export const SET_WINELIST = 'SET_WINELIST'
export const SET_WINE = 'SET_WINE'